services:
  web:
    build: .
    container_name: codeigniter4_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./writable:/var/www/html/writable
      # Mantener vendor del contenedor (no montar desde host)
      - /var/www/html/vendor
    environment:
      - CI_ENVIRONMENT=development
    depends_on:
      - db
    networks:
      - ci4_network

  db:
    image: mysql:8.0
    container_name: codeigniter4_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ci4_database
      MYSQL_USER: ci4_user
      MYSQL_PASSWORD: ci4_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ci4_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: codeigniter4_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - ci4_network

volumes:
  db_data:

networks:
  ci4_network:
    driver: bridge
